btn_origin = "//*[@data-ui-name='input_location_from_segment_0']"
input_origin = "//*[@class='AutoComplete-module__textInput___Qh3I- ']"
btn_destination = "//*[@data-ui-name='input_location_to_segment_0']"
input_destination = "//*[@class='AutoComplete-module__textInput___Qh3I- ']"
btn_search = "//*[@data-ui-name='button_search_submit']"
autosuggestion = "//*[@id='flights-searchbox_suggestions']//span/b"
tab_flights = "//*[@id='flights']"
alr_filled_field = "//*[@class='Tags-module__text___90E7G']"
value_origin_field = "//*[@data-ui-name='input_location_from_segment_0']/div[1]//*[@class='Text-module__root--variant-body_2___7cHHf']"
value_destination_field="//*[@data-ui-name='input_location_to_segment_0']//*[@class='Text-module__root--variant-body_2___7cHHf']"
all_dates_in_cal = "//*[@class='Calendar-module__date___49U04 Calendar-module__date--hoverable___m4cjU']"
btn_select_dates = "//*[@data-ui-name='button_date_segment_0']"
month = "//*[@class='Calendar-module__monthWrapper___FNL-g']/h3"
btn_forward_cal = "//*[@data-ui-name='calendar_body']/button[2]"
flight_details = "//*[@aria-label='Flight option']"
alterate_dates = "//*[@aria-label='Alternative dates with prices']//div/div[1]"
error_destination_field = "//*[@class='ErrorMessage-module__content___nDCzG']"
empty_flights = '//*[text() = "We can’t find any flights that match your search"]'