btn_origin = "//*[@data-ui-name='input_location_from_segment_0']"
input_origin = "//*[@class='AutoComplete-module__textInput___Qh3I- ']"
btn_destination = "//*[@data-ui-name='input_location_to_segment_0']"
input_destination = "//*[@class='AutoComplete-module__textInput___Qh3I- ']"
btn_search = "//*[@data-ui-name='button_search_submit']"
autosuggestion = "//*[@id='flights-searchbox_suggestions']//span/b"
tab_flights = "//*[@id='flights']"
alr_filled_field = "//*[@class='Tags-module__text___90E7G']"
value_origin_field = "//*[@data-ui-name='input_location_from_segment_0']"
value_destination_field="//*[@data-ui-name='input_location_to_segment_0']"
all_dates_in_cal = "//*[contains(@role,'gridcell')]"
btn_select_dates = "//*[@data-ui-name='button_date_segment_0']"
month = "//h3[@aria-live='polite' ]"
btn_forward_cal = "//*[@data-ui-name='calendar_body']/button[2]"
flight_details = "//*[@aria-label='Flight option']"
alterate_dates = "//*[@aria-label='Alternative dates with prices']//div/div[1]"
error_destination_field = "//*[@class='ErrorMessage-module__content___nDCzG']"
empty_flights = '//*[text() = "We can’t find any flights that match your search"]'
popup = '//*[@class="f0c216ee26 c676dd76fe b5018b639f" and @role="dialog"]'
popup_close = '//*[@aria-label="Dismiss sign-in info."]'
